cardinalcarts/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard/<int:product_id>/', views.view_order, name='view_order'),
    path('login', views.login_view, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout_view, name='logout'),
    path('cart', views.cart, name='cart'),
    path('cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('wishlist', views.wishlist, name='wishlist'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('admininventory', views.adminInventory, name='adminInventory'),
    path('admininventory/add/', views.add_product, name='add_product'),
    path('admininventory/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('admininventory/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('adminorder', views.adminOrder, name='adminOrder'),
    path('adminorder/delete/', views.delete_order, name='delete_order'),
    path('adminorder/add/', views.add_order, name='add_order'),
    path('adminorder/edit/', views.edit_order, name='edit_order'),
    path('admintransaction', views.adminTransaction, name='adminTransaction'),
    path('admin', views.adminUser, name='adminUser'),
    path('admin/add/', views.add_user, name='add_user'),
    path('admin/delete/', views.delete_user, name='delete_user'),
    path('admin/edit/', views.edit_user, name='edit_user'),
    path('orderhistory', views.orderHistory, name='orderHistory'),
    path('vieworder', views.viewOrder, name='viewOrder'),
    path('userlog/', views.user_log, name='user_action_log'),
    path('orderlog/', views.order_action_log, name='order_action_log'),
    path('productlog/', views.product_action_log, name='product_action_log'),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify_email'),
    path('admin/orders/delete/<int:order_id>/', views.delete_order_by_id, name='delete_order_by_id'),
    path('inventory/visualization/', views.inventory_visualization, name='inventory_visualization'),
    path('inventory/visualization/download/', views.download_inventory_report, name='download_inventory_report'),
    path('transactions/visualization/download/', views.download_transactions_report, name='download_transactions_report'),
    path('admin/user/delete/<int:user_id>/', views.delete_user_by_id, name='delete_user_by_id'),
]

cardinalcarts/cardinalcarts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('superuser/', admin.site.urls),
    path('', include('base.urls'))
]

cardinalcarts/base/models.py
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    USER_STATUS_CHOICES = [
        ('student', 'Student'),
        ('faculty', 'Faculty'),
        ('staff', 'Staff'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15)
    user_status = models.CharField(max_length=10, choices=USER_STATUS_CHOICES)

    def __str__(self):
        return self.user.username
    
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    category = models.CharField(max_length=100, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.IntegerField()

    def __str__(self):
        return self.name
    
class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    @property
    def total_price(self):
        return self.product.price * self.quantity
    
class WishlistItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"Wishlist item for {self.user.username} - {self.product.name}"
    
class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('Processing', 'Processing'),
        ('Ready for Pickup', 'Ready for Pickup'),
        ('Completed', 'Completed'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_number = models.CharField(max_length=20, unique=True)
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='Processing')
    payment_method = models.CharField(max_length=20)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    order_date = models.DateTimeField(auto_now_add=True)
    pickup_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.order_number} - {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def save(self, *args, **kwargs):
        # Calculate the total price (price * quantity)
        self.total_price = self.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.product.name} (x{self.quantity})"
    
class Transaction(models.Model):
    order_number = models.CharField(max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.TextField(default="No items")
    date_of_order = models.DateField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Transaction {self.order_number}"

class UserActionLog(models.Model):
    ACTION_CHOICES = [
        ('add', 'Add'),
        ('edit', 'Edit'),
        ('delete', 'Delete'),
    ]

    action_type = models.CharField(max_length=10, choices=ACTION_CHOICES)
    admin_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='action_logs')
    timestamp = models.DateTimeField(auto_now_add=True)
    details = models.TextField()

    def __str__(self):
        return f"{self.action_type.capitalize()} action on {self.target_user.get_full_name()} by {self.admin_user.get_full_name()}"
    
class OrderActionLog(models.Model):
    ACTION_CHOICES = [
        ('add', 'Add'),
        ('edit', 'Edit'),
        ('delete', 'Delete'),
    ]

    action_type = models.CharField(max_length=10, choices=ACTION_CHOICES)
    admin_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order_action_logs')
    timestamp = models.DateTimeField(auto_now_add=True)
    details = models.TextField()

    def __str__(self):
        return f"{self.action_type.capitalize()} action on Order #{self.order.order_number} by {self.admin_user.get_full_name()}"
    
class ProductActionLog(models.Model):
    ACTION_CHOICES = [
        ('add', 'Add'),
        ('edit', 'Edit'),
        ('delete', 'Delete'),
    ]
    
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product_name = models.CharField(max_length=255)
    action = models.CharField(max_length=10, choices=ACTION_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True)
    details = models.TextField()

    def __str__(self):
        return f"{self.product_name} - {self.action} by {self.admin}"

cardinalcarts/base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm, ProductForm
from .models import Profile, Product, CartItem, WishlistItem, OrderItem, Order, Transaction, UserActionLog, OrderActionLog, ProductActionLog
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponseForbidden
from django.contrib import messages
from django.db.models import Q
from django.utils import timezone
from datetime import timedelta, datetime, date
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound
import csv
import random

MAX_ATTEMPTS = 5
LOCKOUT_TIME = 300

def verify_email(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (User.DoesNotExist, ValueError, TypeError, OverflowError):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        auth_login(request, user)
        return redirect('dashboard')
    else:
        return render(request, 'verification_failed.html')

def send_verification_email(request, user):
    token = default_token_generator.make_token(user)
    uid = urlsafe_base64_encode(force_bytes(user.pk))
    verification_url = request.build_absolute_uri(
        reverse('verify_email', kwargs={'uidb64': uid, 'token': token})
    )

    send_mail(
        subject='Verify Your Email - CardinalCarts',
        message=f'Hi {user.first_name},\n\nClick the link below to verify your account:\n\n{verification_url}\n\nThank you!',
        from_email='noreply@cardinalcarts.com',
        recipient_list=[user.email],
    )

def login_view(request):
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('adminUser')
        return redirect('dashboard')
    
    if 'login_attempts' not in request.session:
        request.session['login_attempts'] = 0
        request.session['last_attempt_time'] = str(timezone.now())

    last_attempt_time = timezone.datetime.fromisoformat(request.session['last_attempt_time'])

    if request.session['login_attempts'] >= MAX_ATTEMPTS:
        if timezone.now() - last_attempt_time < timedelta(seconds=LOCKOUT_TIME):
            time_left = timedelta(seconds=LOCKOUT_TIME) - (timezone.now() - last_attempt_time)
            minutes, seconds = divmod(time_left.seconds, 60)
            return render(request, 'login.html', {
                'error': f'Too many login attempts. Try again in {minutes}m {seconds}s'
            })
        else:
            request.session['login_attempts'] = 0

    context = {}

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
            auth_user = authenticate(request, username=user.username, password=password)
            if auth_user:
                auth_login(request, auth_user)
                request.session['login_attempts'] = 0
                if auth_user.is_staff:
                    return redirect('adminInventory')
                return redirect('dashboard')
            else:
                request.session['login_attempts'] += 1
                request.session['last_attempt_time'] = str(timezone.now())
                context['error'] = f"Incorrect email or password. Attempts left: {MAX_ATTEMPTS - request.session['login_attempts']}"
        except User.DoesNotExist:
            request.session['login_attempts'] += 1
            request.session['last_attempt_time'] = str(timezone.now())
            context['error'] = f"Incorrect email or password. Attempts left: {MAX_ATTEMPTS - request.session['login_attempts']}"

    return render(request, 'login.html', context)


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)

            user.username = user.username.lower()
            user.first_name = user.first_name.lower()
            user.last_name = user.last_name.lower()

            user.set_password(form.cleaned_data['password'])
            user.is_active = False  # 👈 prevent login until verified

            if form.cleaned_data['user_status'] == 'staff':
                user.is_staff = True

            user.save()

            Profile.objects.create(
                user=user,
                phone_number=form.cleaned_data['phone_number'],
                user_status=form.cleaned_data['user_status']
            )

            send_verification_email(request, user)

            return render(request, 'verification_sent.html')
    else:
        form = RegisterForm()
    
    return render(request, 'register.html', {'form': form})


@require_POST
def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def dashboard(request):
    query = request.GET.get('q', '')
    ready_orders = Order.objects.filter(status="Ready for Pickup", user=request.user)

    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query) |
            Q(category__icontains=query)
        )
    else:
        products = Product.objects.all()

    return render(request, 'dashboard.html', {
        'products': products,
        'query': query,
        'ready_orders': ready_orders
    })


@login_required
def view_order(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'viewOrder.html', {'product': product})


@login_required
def wishlist(request):
    query = request.GET.get("q")
    products = Product.objects.filter(name__icontains=query) if query else Product.objects.all()
    ready_orders = Order.objects.filter(status="Ready for Pickup", user=request.user)
    wishlist_items = WishlistItem.objects.filter(user=request.user)
    return render(request, 'wishlist.html', {'wishlist_items': wishlist_items, 'ready_orders': ready_orders})


@login_required
def add_to_wishlist(request, product_id):
    product = Product.objects.get(id=product_id)

    if not WishlistItem.objects.filter(user=request.user, product=product).exists():

        WishlistItem.objects.create(user=request.user, product=product)

    return redirect('wishlist')


@login_required
def remove_from_wishlist(request):
    if request.method == "POST":
        # Get selected items to remove
        selected_items = request.POST.getlist('remove_items')
        WishlistItem.objects.filter(id__in=selected_items).delete()
    return redirect('wishlist')

@login_required
def cart(request):
    query = request.GET.get("q")
    products = Product.objects.filter(name__icontains=query) if query else Product.objects.all()

    ready_orders = Order.objects.filter(status="Ready for Pickup", user=request.user)
    cart_items = CartItem.objects.filter(user=request.user)
    return render(request, 'cart.html', {'cart_items': cart_items, 'ready_orders': ready_orders})


@login_required
def add_to_cart(request, product_id):
    if request.method == 'POST':
        product = get_object_or_404(Product, id=product_id)
        quantity = int(request.POST.get('quantity', 1))

        cart_item, created = CartItem.objects.get_or_create(user=request.user, product=product)
        if not created:
            cart_item.quantity += quantity
        else:
            cart_item.quantity = quantity
        cart_item.save()

        return redirect('cart')


@login_required
def remove_from_cart(request):
    if request.method == "POST":
        item_ids = request.POST.getlist('remove_items')
        CartItem.objects.filter(id__in=item_ids, user=request.user).delete()
    return redirect('cart')


@login_required
def orderHistory(request):
    query = request.GET.get("q")
    products = Product.objects.filter(name__icontains=query) if query else Product.objects.all()
    ready_orders = Order.objects.filter(status="Ready for Pickup", user=request.user)
    orders = Order.objects.filter(user=request.user).order_by('-order_date')
    for order in orders:
        total_price = 0
        for item in order.items.all():
            
            if item.total_price is None:
                item.total_price = item.product.price * item.quantity
            total_price += item.total_price
        order.total_price = total_price
        
    return render(request, 'orderHistory.html', {'orders': orders, 'ready_orders': ready_orders})


@login_required
def checkout(request):
    if request.method == 'POST':
        payment_method = request.POST.get('payment_method')
        selected_items = CartItem.objects.filter(user=request.user)
        if not selected_items:
            return redirect('cart')
        
        order_number = f"{random.randint(10000000, 99999999)}"
        total_amount = sum(item.total_price for item in selected_items)

        order = Order.objects.create(
            user=request.user,
            order_number=order_number,
            status='Processing',
            payment_method=payment_method,
            total_amount=total_amount,
        )

        for item in selected_items:
            OrderItem.objects.create(
                order=order,
                product=item.product,
                quantity=item.quantity,
                price=item.product.price
            )

cardinalcarts/base/templates/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Add Product</title>
  <link rel="stylesheet" href="{% static 'css/add_product.css' %}" />
</head>
<body>

<header>
  <div class="logoimg">
    <a href="{% url 'dashboard' %}">
      <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo" />
    </a>
    <h1>ADMIN</h1>
  </div>
  
  <nav class="navbar">
    <a href="{% url 'adminTransaction' %}">Transactions</a>
    <a href="{% url 'adminUser' %}">User</a>
    <a href="{% url 'adminInventory' %}">Inventory</a>
    <a href="{% url 'adminOrder' %}">Orders</a>
    <a href="{% url 'dashboard' %}" class="home-btn">HOME</a>
    <form method="POST" action="{% url 'logout' %}">
      {% csrf_token %}
      <button type="submit" class="logout-btn">Logout</button>
    </form>
  </nav>
</header>

<main>
  <div class="form-container">
    <h2>Add Product</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="submit-btn">Add Product</button>
    </form>
  </div>
</main>

</body>
</html>

cardinalcarts/base/templates/adminOrder.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin Orders</title>
  <link rel="stylesheet" href="{% static 'css/adminOrder.css' %}">
</head>
<body>
    <header>
        <div class="logoimg">
            <a href="{% url 'dashboard' %}">
                <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo" />
              </a>
            <H1>ADMIN</H1>
        </div>
        
        <nav class="navbar">
            <a href="{% url 'inventory_visualization' %}">Report</a>
            <a href="{% url 'adminTransaction' %}">Transactions</a>
            <a href="{% url 'adminUser' %}">User</a>
            <a href="{% url 'adminInventory' %}">Inventory</a>
            <a href="{% url 'adminOrder' %}" class="active">Orders</a>
            <a href="{% url 'dashboard' %}" class="home-btn">HOME</a>
            <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="logout-btn">Logout</button>
            </form>
        </nav>
    </header>
    
    <main>
        <div class="Controls">
            <a href="{% url 'add_order' %}">
                <button class="Controls-btn">Add Order</button>
            </a>
            <a href="{% url 'delete_order' %}">
                <button class="Controls-btn">Delete</button>
            </a>
            <a href="{% url 'edit_order' %}">
                <button class="Controls-btn">Edit</button>
            </a>
            <a href="{% url 'order_action_log' %}">
                <button class="Controls-btn">Logs</button>
            </a>
        </div>
        <div class="container">
            <table>
                <thead>
                <tr>
                    <th>Items</th>
                    <th>Order Number</th>
                    <th>Recipient</th>
                    <th>Amount to be Paid</th>
                    <th>Status</th>
                    <th>Pickup Date</th>
                    <th>Actions</th>  <!-- Add this -->
                </tr>
                </thead>
                <tbody>
                {% for order in orders %}
                <tr>
                    <td>
                    {% for item in order.items.all %}
                        {{ item.product.name }} ({{ item.quantity }})<br>
                    {% endfor %}
                    </td>
                    <td>{{ order.order_number }}</td>
                    <td>{{ order.user.get_full_name }}</td>
                    <td>₱{{ order.total_price|floatformat:2 }}</td>
                    <td>{{ order.status|capfirst }}</td>
                    <td>
                    {% if order.pickup_date %}
                        {{ order.pickup_date }}
                    {% else %}
                        Pending
                    {% endif %}
                    </td>
                    <td>
                        <form method="GET" action="{% url 'edit_order' %}" style="display:inline;">
                            <input type="hidden" name="order_number" value="{{ order.order_number }}">
                            <button type="submit" class="edit-btn">Edit</button>
                        </form>
                        
                        <form method="POST" action="{% url 'delete_order_by_id' order.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="delete-btn" onclick="return confirm('Delete order {{ order.order_number }}?')">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

cardinalcarts/base/templates/adminUser.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Admin User Management</title>
  <link rel="stylesheet" href="{% static 'css/adminUser.css' %}">
</head>
<body>
    <header>
        <div class="logoimg">
            <a href="{% url 'dashboard' %}">
                <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo" />
            </a>
            <h1>ADMIN</h1>
        </div>
        <nav class="navbar">
            <a href="{% url 'inventory_visualization' %}">Report</a>
            <a href="{% url 'adminTransaction' %}">Transactions</a>
            <a href="{% url 'adminUser' %}" class="active">User</a>
            <a href="{% url 'adminInventory' %}">Inventory</a>
            <a href="{% url 'adminOrder' %}">Orders</a>
            <a href="{% url 'dashboard' %}" class="home-btn">HOME</a>
            <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit" class="logout-btn">Logout</button>
              </form>
        </nav>
    </header>
    <main>
        <div class="Controls">
            <a href="{% url 'add_user' %}" class="Controls-btn">Add</a>
            <a href="{% url 'delete_user' %}" class="Controls-btn">Delete</a>
            <a href="{% url 'edit_user' %}" class="Controls-btn">Edit</a>
            <a href="{% url 'user_action_log' %}" class="Controls-btn">Logs</a>
        </div>
        <div class="container">
            <table>
                <thead>
                    <tr>
                        <th>User Id</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th>User Type</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.first_name }} {{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.profile.phone_number }}</td>
                        <td>{{ user.profile.user_status.title }}</td>
                        <td>
                            <!-- Edit Button -->
                            <a href="{% url 'edit_user' %}?user_id={{ user.id }}" class="edit-btn">Edit</a>

                            <!-- Delete Button -->
                            <form action="{% url 'delete_user_by_id' user.id %}" method="POST" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete {{ user.first_name }}?');">
                                {% csrf_token %}
                                <button type="submit" class="delete-btn">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

cardinalcarts/base/templates/dashboard.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>School Supplies</title>
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
    <header>
        <div class="logo-search">
          <a href="{% url 'dashboard' %}">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo" />
          </a>
          <form method="GET" action="{% url 'dashboard' %}">
            <input type="text" name="q" placeholder="Search" class="search-box" value="{{ query|default:'' }}">
          </form>
        </div>
        <nav class="navbar">
          <div class="notification-dropdown">
            <a href="#" class="notification-link">Notification</a>
            <div class="notification-content">
              {% if ready_orders %}
                {% for order in ready_orders %}
                  <div class="notification-item">
                    <strong>Order #{{ order.order_number }}</strong><br>
                    Pickup Date: {{ order.pickup_date|default:"N/A" }}
                  </div>
                {% endfor %}
              {% else %}
                <div class="notification-item">No orders ready for pickup.</div>
              {% endif %}
            </div>
          </div>
            <a href="{% url 'cart' %}">Cart</a>
            <a href="{% url 'wishlist' %}" class="active">Wishlists</a>
            <a href="{% url 'orderHistory' %}">Order History</a>
            <a href="{% url 'dashboard' %}" class="home-btn">HOME</a>
            <form method="POST" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="logout-btn">Logout</button>
            </form>
        </nav>
    </header>

  <main>
    <br>
    <br>
    <br>
    <section class="product-grid">
      {% for product in products %}
      <a href="{% url 'view_order' product.id %}">
        <div class="product-card">
          <div class="image-placeholder"></div>
          <p class="product-name">{{ product.name }}</p>
          <p class="product-price">₱{{ product.price|intcomma }}</p>
          <p><span class="category-pill">{{ product.category }}</span></p>
        </div>
      </a>
      {% empty %}
        <p>No products available.</p>
      {% endfor %}
    </section>
  </main>
</body>
</html>

cardinalcarts/base/templates/edit_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edit Product</title>
  <link rel="stylesheet" href="{% static 'css/edit_product.css' %}">
</head>
<body>
  <header>
    <div class="logoimg">
        <a href="{% url 'dashboard' %}">
            <img src="{% static 'images/logo.png' %}" alt="Logo" class="logo" />
          </a>
        <H1>ADMIN</H1>
    </div>
    
    <nav class="navbar">
        <a href="{% url 'adminTransaction' %}">Transactions</a>
        <a href="{% url 'adminUser' %}">User</a>
        <a href="{% url 'adminInventory' %}">Inventory</a>
        <a href="{% url 'adminOrder' %}" class="active">Orders</a>
        <a href="{% url 'dashboard' %}" class="home-btn">HOME</a>
        <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit" class="logout-btn">Logout</button>
        </form>
    </nav>
</header>

<main class="content-wrapper">
  <div class="container">
    <h2>Edit Product</h2>
    <form method="POST" class="form-box">
      {% csrf_token %}

      <label for="id_name">Product Name</label>
      <input type="text" name="name" id="id_name" value="{{ form.name.value }}" required>

      <label for="id_price">Price</label>
      <input type="number" name="price" id="id_price" value="{{ form.price.value }}" min="0" step="0.01" required>

      <label for="id_quantity">Quantity</label>
      <input type="number" name="quantity" id="id_quantity" value="{{ form.quantity.value }}" min="0" required>

      <label for="id_description">Description</label>
      <textarea name="description" id="id_description" rows="4" required>{{ form.description.value }}</textarea>

      <button type="submit" class="submit-btn">Save Changes</button>
    </form>
  </div>
</main>
</body>
</html>

cardinalcarts/base/templates/order_action_log.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Action Logs</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/order_action_log.css' %}">
</head>
<body>

<div class="container">
    <h2>Order Action Logs</h2>
    
    <table>
        <thead>
            <tr>
                <th>Action Type</th>
                <th>Admin User</th>
                <th>Timestamp</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            {% for log in logs %}
                <tr>
                    <td class="action-type">{{ log.get_action_type_display }}</td>
                    <td class="admin-user">{{ log.admin_user.get_full_name }}</td>
                    <td class="timestamp">{{ log.timestamp }}</td>
                    <td class="details">{{ log.details }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'adminOrder' %}" class="back-button">
        <i class="fas fa-arrow-left"></i> Back to Orders
    </a>
</div>

</body>
</html>